image: local-registry.inner.buaaoo.top/image-dev/python:3.5.2-java8

stages:
  - demo
  - unit_test

variables:
  MIN_UNITTEST_COVERAGE: 90
  ENTRANCE_FINDER_RELEASE_URL: '${RELEASE_URL}/dcmodule/dcmodule-{version}.jar'
  TWINE_REPOSITORY: pypi
  OSS_NAME: oss
  OSS_RELEASE_ROOT: ${OSS_NAME}/releases/${CI_PROJECT_NAME}
  OSS_DEV_ROOT: ${OSS_NAME}/dev/${CI_PROJECT_NAME}
  DEMO_ROOT: demo
  DEMO_PATH: ${DEMO_ROOT}/demo_program

before_script:
  - pip config set global.index-url "https://${PYPI_USERNAME}:${PYPI_PASSWORD}@${PYPI_HOST}/simple"
  - pip3 install 'pypirc-chappers>=1' 'twine>=1'
  - pypirc -q -s "${TWINE_REPOSITORY}" -r "${PYPI_URL}" -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}"
  - pip3 install 'pytest>=5' 'pytest-mock' 'pytest-cov'
  - curl -o /usr/bin/mc "${RELEASE_URL}/mc" && chmod +x /usr/bin/mc
  - mc --version
  - mc config host add ${OSS_NAME} "${OSS_URL}" "${OSS_ACCESS_ID}" "${OSS_ACCESS_TOKEN}"
  - mkdir -p ${DEMO_ROOT} && cd ${DEMO_ROOT}
    && for f in $(mc ls ${OSS_DEV_ROOT}/ | awk '{print $5}'); do mc cp ${OSS_DEV_ROOT}/$f $f; done
    && for f in *.tar.gz; do tar -zxvf $f; done
    && cd .. && tree -a ${DEMO_ROOT}

demo_development:
  stage: demo
  script:
    - pip3 install -e .
    - dcmodule_dir=$(pip3 show pyentrance | grep Location | cut -c 11-)/dcmodule
      && tree -a ${dcmodule_dir}
    - cd ${DEMO_ROOT}
    - python3 -c "from dcmodule import *;print(version);"
    - cd ..

demo_production:
  stage: demo
  script:
    - pip3 install .
    - dcmodule_dir=$(pip3 show pyentrance | grep Location | cut -c 11-)/dcmodule
      && tree -a ${dcmodule_dir}
    - cd ${DEMO_ROOT}
    - python3 -c "from dcmodule import *;print(version);"
    - cd ..

unit_test_in_3.5.2:
  stage: unit_test
  image: local-registry.inner.buaaoo.top/image-dev/python:3.5.2-java8
  script:
    - pip3 install -e .
    - pytest --version
    - pytest ./test --cov-report term-missing --cov=./pyentrance -sv -m unittest --cov-fail-under=${MIN_UNITTEST_COVERAGE}

unit_test_in_3.6.3:
  stage: unit_test
  image: local-registry.inner.buaaoo.top/image-dev/python:3.6.3-java8
  script:
    - pip3 install -e .
    - pytest --version
    - pytest ./test --cov-report term-missing --cov=./pyentrance -sv -m unittest --cov-fail-under=${MIN_UNITTEST_COVERAGE}

unit_test_in_3.7.6:
  stage: unit_test
  image: local-registry.inner.buaaoo.top/image-dev/python:3.7.6-java8
  script:
    - pip3 install -e .
    - pytest --version
    - pytest ./test --cov-report term-missing --cov=./pyentrance -sv -m unittest --cov-fail-under=${MIN_UNITTEST_COVERAGE}

unit_test_in_3.8.1:
  stage: unit_test
  image: local-registry.inner.buaaoo.top/image-dev/python:3.8.1-java8
  script:
    - pip3 install -e .
    - pytest --version
    - pytest ./test --cov-report term-missing --cov=./pyentrance -sv -m unittest --cov-fail-under=${MIN_UNITTEST_COVERAGE}
