  name: Init Test

  on:
  - push
  - pull_request

  jobs:
    init:
      name: Init a test for github action
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os:
            - 'ubuntu-18.04'
          python-version:
            - '3.7'
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install python dependencies
          run: |
            python -m pip install --upgrade pip
            pip install --upgrade flake8 setuptools wheel twine
            pip install -r requirements.txt
            pip install -r requirements-test.txt
        - name: Test the basic environment
          run: |
            python -V
            python -c "import sys; print(sys.version)"
            pip --version  
            pip list
            tree .
      